version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: breakfast
    volumes:
      - .:/mnt
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=breakfast
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
