version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: breakfast_at_the_frat_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=breakfast_at_the_frat
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
